service release part1
Mark0VLK/pizza pull request #11
Opened 2024-06-12 12:32 UTC by Zheleznykovich-Maxim

2024-06-12 13:59 UTC, Mark0VLK reviewed
вместо .orElse(null) выкидывать исключения

2024-06-12 13:59 UTC, Mark0VLK commented on pom.xml
> +			<artifactId>mapstruct</artifactId>
вынеси версию в properties

2024-06-12 18:12 UTC, Zheleznykovich-Maxim commented on pom.xml
> +			<artifactId>mapstruct</artifactId>
сделал

2024-06-12 19:46 UTC, egan1k submitted a review, later dismissed

2024-06-13 06:42 UTC, Mark0VLK approved these changes, later dismissed

2024-06-13 07:12 UTC, Maxanko requested changes

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends jakarta.persistence.EntityNotFoundException {
Обычно наследуются от RuntimeException

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/mapper/DishMapper.java
> +@Mapper(uses = {InformationMapper.class})
componentModel = MappingConstants.ComponentModel.SPRING,

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/mapper/DrinkMapper.java
> +@Mapper(uses = {InformationMapper.class})
componentModel = MappingConstants.ComponentModel.SPRING,

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/mapper/CategoryMapper.java
> +@Mapper
componentModel = MappingConstants.ComponentModel.SPRING,

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/mapper/InformationMapper.java
> +@Mapper(uses = {CategoryMapper.class})
componentModel = MappingConstants.ComponentModel.SPRING,

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/CategoryServiceImpl.java
> +        Category category = categoryRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("category", id));
orElseThrow с новой строки должно быть

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/CategoryServiceImpl.java
> +        Category category = categoryRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("category", id));
orElseThrow должно быть с новой строки

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/DishServiceImpl.java
> +        Dish dish = dishRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("dish", id));
orElseThrow должно быть с новой строки

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/DishServiceImpl.java
> +        Dish dish = dishRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("dish", id));
orElseThrow должно быть с новой строки

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/DishServiceImpl.java
> +        dish.setInformation(information);
Вот это можно вынести в отдельный метод

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/DishServiceImpl.java
> +        Dish dish = dishRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("dish", id));
orElseThrow должно быть с новой строки

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/DrinkServiceImpl.java
> +        Drink drink = drinkRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("drink", id));
orElseThrow должно быть с новой строки

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/DrinkServiceImpl.java
> +        Drink drink = drinkRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("drink", id));
orElseThrow должно быть с новой строки

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/DrinkServiceImpl.java
> +        Drink drink = drinkRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("drink", id));
orElseThrow должно быть с новой строки

2024-06-13 07:12 UTC, Maxanko commented on src/main/java/com/example/pizza/service/impl/InformationServiceImpl.java
> +        information.setImage(informationUpdateRequest.image());
Вот это нужно в отдельный метод вынести

2024-06-13 10:53 UTC, Mark0VLK approved these changes

2024-06-13 12:45 UTC, egan1k approved these changes

2024-06-13 12:53 UTC, Zheleznykovich-Maxim commented on src/main/java/com/example/pizza/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends jakarta.persistence.EntityNotFoundException {
исправил

2024-06-13 12:54 UTC, Zheleznykovich-Maxim commented on src/main/java/com/example/pizza/mapper/DishMapper.java
> +@Mapper(uses = {InformationMapper.class})
добавил

2024-06-13 12:54 UTC, Zheleznykovich-Maxim commented on src/main/java/com/example/pizza/service/impl/InformationServiceImpl.java
> +        information.setImage(informationUpdateRequest.image());
создал

2024-06-13 12:55 UTC, Zheleznykovich-Maxim commented on src/main/java/com/example/pizza/service/impl/DishServiceImpl.java
> +        dish.setInformation(information);
добавил

2024-06-14 10:39 UTC, Maxanko approved these changes

2024-06-14 10:53 UTC, merged