added service level of interfaces and classes
Mark0VLK/pizza pull request #8
Opened 2024-06-07 19:18 UTC by egan1k

added service level of interfaces and classes for each entity
добавлен сервис слой с интерфейсами и классами для каждой сущности

2024-06-08 07:25 UTC, Mark0VLK commented
Необходимо добавить аннотацию Service над классами, которые реализуют интерфейсы

2024-06-08 07:28 UTC, Mark0VLK commented
добавить отступы между методами в интерфейсах

2024-06-08 07:30 UTC, Mark0VLK requested changes

2024-06-08 07:30 UTC, Mark0VLK commented on src/main/java/com/example/pizza/service/impl/DishOrderServiceImpl.java
> +
забыл добавить аннотацию Service

2024-06-08 07:30 UTC, Mark0VLK commented on src/main/java/com/example/pizza/service/impl/DishServiceImpl.java
> +
добавить аннотацию Service

2024-06-08 07:32 UTC, Mark0VLK commented on src/main/java/com/example/pizza/service/impl/DrinkOrderServiceImpl.java
> +public class DrinkOrderServiceImpl implements DrinkOrderService {
добавить отступ

2024-06-08 08:38 UTC, Mark0VLK submitted a review, later dismissed

2024-06-08 08:52 UTC, Mark0VLK approved these changes, later dismissed

2024-06-09 10:31 UTC, Zheleznykovich-Maxim approved these changes, later dismissed
i approve

2024-06-10 09:03 UTC, Mark0VLK approved these changes, later dismissed

2024-06-10 09:26 UTC, nostrumee reviewed
Хорошо подобраны названия для дто, отмечу только пару моментов:
Методы сервисов должны возвращать не сущности, а дто (респонсы)
Насчет update реквестов - не совсем понятен их смысл. В дто должны содержаться уже новые значения полей для обновляемой сущности, а айди сущности которую нужно обновить можно передать просто как дополнительный параметр

2024-06-10 09:26 UTC, nostrumee commented on pom.xml
> +			<version>${spring-boot-starter-validation.version}</version>
тут не обязательно указывать версию, версии для стартеров подтягиваются из parent. а вот в других зависимостях уже следует это сделать

2024-06-10 09:26 UTC, nostrumee commented on src/main/java/com/example/pizza/PizzaApplication.java
> +//		System.setProperty("db_password", "postgres");
убрать комментарии

2024-06-10 09:26 UTC, nostrumee commented on src/main/java/com/example/pizza/request/category/CategoryCreateRequest.java
дто можно делать рекордами

2024-06-10 09:26 UTC, nostrumee commented on src/main/java/com/example/pizza/request/category/CategoryCreateRequest.java
> +    @Size(max = 50, message = "Name must be less than 50 characters")
сообщения валидации лучше выносить в отдельный файл, чтобы чуть что можно было локализацию делать да и просто для лучше поддерживаемости. вот тут вкратце показано как это делать
https://www.baeldung.com/spring-custom-validation-message-source

2024-06-10 09:26 UTC, nostrumee commented on src/main/java/com/example/pizza/service/CategoryService.java
> +    Category deleteById(Long id, boolean forever);
передавать какой-то флаг в виде булеан считается плохой практикой, потому что при вызове метода не всегда понятно что мы имеем в виду при вызове этого метода передавая true или false. Вариантов решить это несколько, один из них - создать енам например с названием DeleteMode и передавать его вместо булеан

2024-06-10 15:27 UTC, Mark0VLK submitted a review, later dismissed

2024-06-10 15:28 UTC, Mark0VLK commented on pom.xml
> +			<version>${spring-boot-starter-validation.version}</version>
убрали

2024-06-10 15:28 UTC, Mark0VLK commented on src/main/java/com/example/pizza/service/CategoryService.java
> +    Category deleteById(Long id, boolean forever);
исправили

2024-06-10 15:28 UTC, Mark0VLK commented on src/main/java/com/example/pizza/request/category/CategoryCreateRequest.java
> +    @Size(max = 50, message = "Name must be less than 50 characters")
вынесли

2024-06-10 15:29 UTC, Mark0VLK commented on src/main/java/com/example/pizza/PizzaApplication.java
> +//		System.setProperty("db_password", "postgres");
убрали

2024-06-10 15:29 UTC, Mark0VLK commented on src/main/java/com/example/pizza/request/category/CategoryCreateRequest.java
исправили

2024-06-10 15:50 UTC, nostrumee reviewed
в целом все хорошо, единственное что я не имел в виду что update реквесты вообще не нужны ) я имел в виду, что их содержимое было неправильным

в общем, в update методы нужно передавать айди и update реквесты (часто их содержимое будет дублировать содержимое create реквестов, но не всегда так выходит)

2024-06-10 15:50 UTC, nostrumee commented on src/main/java/com/example/pizza/service/impl/CategoryServiceImpl.java
> +    public CategoryResponse update(Long Id, CategoryCreateRequest categoryCreateRequest) {
тут id с маленькой буквы нужно

2024-06-10 15:53 UTC, Zheleznykovich-Maxim approved these changes, later dismissed
i approve all changes

2024-06-10 17:36 UTC, Zheleznykovich-Maxim approved these changes
i approve bug fixes

2024-06-10 17:37 UTC, Mark0VLK approved these changes

2024-06-10 17:41 UTC, Mark0VLK commented on src/main/java/com/example/pizza/service/impl/CategoryServiceImpl.java
> +    public CategoryResponse update(Long Id, CategoryCreateRequest categoryCreateRequest) {
исправили

2024-06-10 17:46 UTC, nostrumee approved these changes

2024-06-10 17:52 UTC, merged